apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-cpu
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          env:
            - name: NGINX_PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200M
              cpu: 1000
