apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: low-mem
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: low-mem
  targetCPUUtilizationPercentage: 50
